name: veeki
description: A new Caregiver project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.4
  intl: ^0.17.0
  table_calendar: ^3.0.8
  timelines:
  banner_carousel: ^1.2.1
  anim_search_bar: ^2.0.3
  dropdown_button2: ^2.1.0
  carousel_slider: ^4.0.0
  introduction_screen: ^3.1.8
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  http: ^0.13.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: 9.1.0

  awesome_dialog:
  connectivity_plus: ^1.0.6
  image_picker: ^0.8.7+5
  url_launcher: ^6.0.9
  photo_view: ^0.14.0
  permission_handler: ^8.1.4+2
  email_validator: ^2.0.1
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.11

  badges: ^2.0.1
  flutter_rating_bar: ^4.0.0
  flutter_timezone: ^1.0.4
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  flutter_local_notifications: ^14.1.1
  geolocator: ^7.0.1
  shimmer: ^2.0.0
  scratcher: ^2.1.0
  cached_network_image:
  geocoding: ^2.0.1
  device_info_plus: ^8.0.0
  hive_flutter: ^1.1.0
  hive:
  flutter_paystack: ^1.0.7
  assets_audio_player: ^3.0.6
  latlng: ^0.1.0
  fluttertoast: ^8.0.7

  toast: ^0.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
 # android: "ic_launcher"
  android: true
  ios: true
  remove_alpha_ios: true
  #image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  #adaptive_icon_foreground: "assets/logo.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/
    - Images/profilepicture.png
    - Images/download.png
    - Images/HomepageBannerImage.png
    - Images/HomepageBannerImage2.png
    - Images/HomepageBannerImage3.png
    - Images/Products.png
    - Images/clippers.png
    - Images/barber.png
    - Images/Barbershop.png
    - Images/barbing.png
    - Images/paystack.png
    - Images/payxpress.png
    - Images/payxpress1.png
    - Images/payment.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/roboto/Roboto-Regular.ttf
         - asset: assets/fonts/roboto/Roboto-Italic.ttf
           style: italic
         - asset: assets/fonts/roboto/Roboto-Black.ttf
           weight: 700
         - asset: assets/fonts/roboto/Roboto-Bold.ttf
           weight: 600
         - asset: assets/fonts/roboto/Roboto-Medium.ttf
           weight: 500
         - asset: assets/fonts/roboto/Roboto-Regular.ttf
           weight: 400

     - family: Lato
       fonts:
         - asset: assets/fonts/lato/Lato-Regular.ttf
         - asset: assets/fonts/lato/Lato-Bold.ttf
           weight: 700
         - asset: assets/fonts/lato/Lato-Heavy.ttf
           weight: 600
         - asset: assets/fonts/lato/Lato-Medium.ttf
           weight: 500
         - asset: assets/fonts/lato/Lato-Regular.ttf
           weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
