// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///Platform  Firebase App Id
// android   1:618042020782:android:69f54454741008d7fc2e3f
// ios       1:618042020782:ios:9911f099d00f3c3cfc2e3f
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAjpVqr_YEA912OtzMRZmjGPsvlRBK6nY',
    appId: '1:618042020782:android:69f54454741008d7fc2e3f',
    messagingSenderId: '618042020782',
    projectId: 'veeki-86fa1',
    storageBucket: 'veeki-86fa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40aO2mUvlZlu9YNFn-s61HIwQaEoN90g',
    appId: '1:618042020782:ios:9911f099d00f3c3cfc2e3f',
    messagingSenderId: '618042020782',
    projectId: 'veeki-86fa1',
    storageBucket: 'veeki-86fa1.appspot.com',
    iosClientId: '618042020782-uckldmff4fiqgctuoq35omep8isaofge.apps.googleusercontent.com',
    iosBundleId: 'co.veeki.veeki',
  );
}
